/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Utils.Auth;
import Utils.MsgBox;
import java.awt.CardLayout;

/**
 *
 * @author THINKPAD
 */
public class Main extends javax.swing.JFrame {

    KhuyenMai km = new KhuyenMai();
    HoaDon hd = new HoaDon();
    QlSanPham sp = new QlSanPham();
    NhanVien_Form nv = new NhanVien_Form();
    KhachHangS kh = new KhachHangS();
    ThongKe tk = new ThongKe();
    BanHang bh = new BanHang();
    DoiMatKhau_Form dmk = new DoiMatKhau_Form();
    private String timeee, tongTienDauCaaa;
    GiaoCa_QuanLy_Form gc = new GiaoCa_QuanLy_Form();

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        setLocationRelativeTo(null);

    }

    public Main(String time, String tongTienDauCa) {
        initComponents();
        setLocationRelativeTo(null);
        Panel3.add(bh, "banhang");
        Panel3.add(hd, "hoadon");
        Panel3.add(km, "khuyenMai");
        Panel3.add(sp, "sanpham");
        Panel3.add(nv, "nhanvien");
        Panel3.add(kh, "khachhang");
        Panel3.add(tk, "thongke");
        Panel3.add(gc, "qlgiaoca");
        Panel3.add(dmk, "doimk");
        boolean user = Auth.isLogin();
        if (user == true) {
            lblUser.setText(Auth.user.getHoTen());
        } else {
            lblUser.setText("NULL");
            MsgBox.alert(this, "Bạn chưa đăng nhập! ");
        }
        this.tongTienDauCaaa = tongTienDauCa;
        this.timeee = time;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel1 = new javax.swing.JPanel();
        Panel2 = new javax.swing.JPanel();
        lblUser = new javax.swing.JLabel();
        btnBanHang = new javax.swing.JButton();
        btnSanPham = new javax.swing.JButton();
        btnHoaDon = new javax.swing.JButton();
        btnKhuyenMai = new javax.swing.JButton();
        btnKhachhang = new javax.swing.JButton();
        btnThongKe = new javax.swing.JButton();
        btnNhanVien = new javax.swing.JButton();
        btnQuanLyCa = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnGiaoCa = new javax.swing.JButton();
        Panel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panel1.setBackground(new java.awt.Color(255, 204, 51));

        Panel2.setBackground(new java.awt.Color(255, 255, 204));
        Panel2.setLayout(new java.awt.GridLayout(11, 1, 10, 10));

        lblUser.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblUser.setForeground(new java.awt.Color(204, 0, 51));
        lblUser.setText("UserName");
        Panel2.add(lblUser);

        btnBanHang.setBackground(new java.awt.Color(255, 153, 0));
        btnBanHang.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnBanHang.setText("Bán Hàng");
        btnBanHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBanHangActionPerformed(evt);
            }
        });
        Panel2.add(btnBanHang);

        btnSanPham.setBackground(new java.awt.Color(255, 153, 0));
        btnSanPham.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnSanPham.setText("Sản Phẩm");
        btnSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSanPhamActionPerformed(evt);
            }
        });
        Panel2.add(btnSanPham);

        btnHoaDon.setBackground(new java.awt.Color(255, 153, 0));
        btnHoaDon.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnHoaDon.setText("Hóa Đơn");
        btnHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHoaDonActionPerformed(evt);
            }
        });
        Panel2.add(btnHoaDon);

        btnKhuyenMai.setBackground(new java.awt.Color(255, 153, 0));
        btnKhuyenMai.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnKhuyenMai.setText("Khuyến Mại");
        btnKhuyenMai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhuyenMaiActionPerformed(evt);
            }
        });
        Panel2.add(btnKhuyenMai);

        btnKhachhang.setBackground(new java.awt.Color(255, 153, 0));
        btnKhachhang.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnKhachhang.setText("Khách Hàng");
        btnKhachhang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhachhangActionPerformed(evt);
            }
        });
        Panel2.add(btnKhachhang);

        btnThongKe.setBackground(new java.awt.Color(255, 153, 0));
        btnThongKe.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnThongKe.setText("Thống Kê");
        btnThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeActionPerformed(evt);
            }
        });
        Panel2.add(btnThongKe);

        btnNhanVien.setBackground(new java.awt.Color(255, 153, 0));
        btnNhanVien.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnNhanVien.setText("Nhân Viên");
        btnNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhanVienActionPerformed(evt);
            }
        });
        Panel2.add(btnNhanVien);

        btnQuanLyCa.setBackground(new java.awt.Color(255, 153, 0));
        btnQuanLyCa.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnQuanLyCa.setText("Quản lý Ca");
        btnQuanLyCa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyCaActionPerformed(evt);
            }
        });
        Panel2.add(btnQuanLyCa);

        jButton1.setBackground(new java.awt.Color(255, 153, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Đổi Mật Khẩu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Panel2.add(jButton1);

        btnGiaoCa.setBackground(new java.awt.Color(255, 153, 0));
        btnGiaoCa.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnGiaoCa.setText("Giao Ca");
        btnGiaoCa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGiaoCaActionPerformed(evt);
            }
        });
        Panel2.add(btnGiaoCa);

        Panel3.setBackground(new java.awt.Color(255, 255, 255));
        Panel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Panel3.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout Panel1Layout = new javax.swing.GroupLayout(Panel1);
        Panel1.setLayout(Panel1Layout);
        Panel1Layout.setHorizontalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panel2, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Panel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel1Layout.setVerticalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Panel2, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
                    .addComponent(Panel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBanHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBanHangActionPerformed
        bh.changeCard();
        CardLayout cardLayout = (CardLayout) Panel3.getLayout();
        cardLayout.show(Panel3, "banhang");
    }//GEN-LAST:event_btnBanHangActionPerformed


    private void btnHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHoaDonActionPerformed
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) Panel3.getLayout();
        cardLayout.show(Panel3, "hoadon");
        hd.changeCard();
    }//GEN-LAST:event_btnHoaDonActionPerformed

    private void btnSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSanPhamActionPerformed
        CardLayout cardLayout = (CardLayout) Panel3.getLayout();
        cardLayout.show(Panel3, "sanpham");
    }//GEN-LAST:event_btnSanPhamActionPerformed

    private void btnKhuyenMaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhuyenMaiActionPerformed
        // TODO add your handling code here:
        km.changeCard();
        CardLayout cardLayout = (CardLayout) Panel3.getLayout();
        cardLayout.show(Panel3, "khuyenMai");
    }//GEN-LAST:event_btnKhuyenMaiActionPerformed

    private void btnNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhanVienActionPerformed
        if (Auth.isManager() == true) {
            CardLayout cardLayout = (CardLayout) Panel3.getLayout();
            cardLayout.show(Panel3, "nhanvien");
        } else {
            MsgBox.alert(this, "Bạn không có quyền mở quản lý nhân viên!");
        }

    }//GEN-LAST:event_btnNhanVienActionPerformed

    private void btnKhachhangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhachhangActionPerformed
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) Panel3.getLayout();
        cardLayout.show(Panel3, "khachhang");
    }//GEN-LAST:event_btnKhachhangActionPerformed

    private void btnThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKeActionPerformed
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) Panel3.getLayout();
        cardLayout.show(Panel3, "thongke");
        tk.test();
    }//GEN-LAST:event_btnThongKeActionPerformed

    private void btnGiaoCaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGiaoCaActionPerformed
        // TODO add your handling code here:
        new GiaoCa2_Form(timeee, tongTienDauCaaa).setVisible(true);

    }//GEN-LAST:event_btnGiaoCaActionPerformed

    private void btnQuanLyCaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyCaActionPerformed
        // TODO add your handling code here:
        if (Auth.isManager() == true) {
            CardLayout cardLayout = (CardLayout) Panel3.getLayout();
            cardLayout.show(Panel3, "qlgiaoca");
        } else {
            MsgBox.alert(this, "Bạn không có quyền mở quản lý nhân viên !");
        }

    }//GEN-LAST:event_btnQuanLyCaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CardLayout cardLayout = (CardLayout) Panel3.getLayout();
        cardLayout.show(Panel3, "doimk");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel1;
    private javax.swing.JPanel Panel2;
    private javax.swing.JPanel Panel3;
    private javax.swing.JButton btnBanHang;
    private javax.swing.JButton btnGiaoCa;
    private javax.swing.JButton btnHoaDon;
    private javax.swing.JButton btnKhachhang;
    private javax.swing.JButton btnKhuyenMai;
    private javax.swing.JButton btnNhanVien;
    private javax.swing.JButton btnQuanLyCa;
    private javax.swing.JButton btnSanPham;
    private javax.swing.JButton btnThongKe;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblUser;
    // End of variables declaration//GEN-END:variables
}
